In [6]:
import torch
#from mock_tensor import MockTensor as torch
import numpy as np
input_list = [[1, 5, 7, 9, 11], [13, 15, 17, 19, 21]]
input_array = np.array([[[15, 17, 11], [19, 14, 13]]])

In [3]:
def create_tensor_from_list(input_list):
    tensor_from_list = torch.tensor(input_list)
    return tensor_from_list

def create_tensor_from_array(input_array):
    tensor_from_array = torch.tensor(input_array)
    return tensor_from_array

#create tensors that have the shape of 3 by 4 filled with ones
def create_tensor_ones():
    tensor_ones= torch.ones(3,4)
    return tensor_ones

#create tensors that have the shape of 4 by 5 filled with 5
def create_tensor_full():
    tensor_full = torch.full((4,5),5)
    return tensor_full

In [10]:
tensor_from_list = create_tensor_from_list(input_list)  
tensor_from_list


tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])

In [9]:
tensor_from_array = create_tensor_from_array(input_array)
tensor_from_array


tensor([[ 1,  5,  7,  9, 11],
        [13, 15, 17, 19, 21]])

In [11]:
ones_tensor = create_tensor_ones()
ones_tensor


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
full_tensor = create_tensor_full()
full_tensor

tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])