In [1]:
import torch
import numpy as np

## Generate a simple starting tensor

In [3]:
starting_tensor = torch.zeros(2,5)
print(starting_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


## Mimic Shape
To mimic the shape of another tensor you can use the other tensor as a model using the _like(tensor_of_interest)
### Mimic the shape of a tensor using random numbers from 0-1

In [4]:
#creates a tensor of random numbers using a seed that will have the same dimensions as starting tensor
torch.manual_seed(111)
rand_tensor =  torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

### Mimic the shape of the tensor filled with ones

In [7]:
#creates a tensor of 1s that will have the same dimensions as starting tensor
ones_tensor =  torch.ones_like(starting_tensor)
ones_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Mimic the shame of the given tensor filled with a set value

In [8]:

full_tensor =  torch.full_like(starting_tensor, 7)
full_tensor

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])